# Generated by Django 4.1.6 on 2023-02-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistick', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fquestion',
            options={'verbose_name': 'Fquestion'},
        ),
    ]
