# Generated by Django 4.1.6 on 2023-02-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistick', '0002_alter_fquestion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fquestion',
            options={'verbose_name': 'F_user_details'},
        ),
        migrations.RenameField(
            model_name='fquestion',
            old_name='answer_Two',
            new_name='answer_two',
        ),
        migrations.AddField(
            model_name='fquestion',
            name='is_Vendor',
            field=models.BooleanField(default=True),
        ),
    ]
