# Generated by Django 4.1.6 on 2023-02-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistick', '0003_alter_fquestion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fquestion',
            old_name='is_Vendor',
            new_name='is_vendor',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('v_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='logistick.fquestion')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='logistick.fquestion')),
                ('stock_id', models.ManyToManyField(to='logistick.stock')),
            ],
        ),
    ]
