# Generated by Django 4.1.6 on 2023-02-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistick', '0007_remove_order_price_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
        migrations.AlterModelOptions(
            name='fquestion',
            options={'verbose_name': 'F_user_detail'},
        ),
    ]
