# Generated by Django 4.1.6 on 2023-02-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistick', '0010_alter_orderdetail_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
