# Generated by Django 4.1.6 on 2023-02-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistick', '0012_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='by',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
