# Generated by Django 4.1.6 on 2023-02-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistick', '0016_bag_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Accepted', 'Accepted'), ('Shipped', 'Shipped'), ('delivered', 'delivered')], default='placed', max_length=10),
        ),
        migrations.AlterField(
            model_name='bag',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
