# Generated by Django 4.1.6 on 2023-03-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistick', '0019_alter_fquestion_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fquestion',
            name='address',
        ),
    ]
