# Generated by Django 4.1.6 on 2023-03-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistick', '0022_alter_fquestion_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
